version: '3.7'

services:
  regression:
    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/workspace
    command: /bin/sh -c "ls && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
