name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: full_regression
        type: choice
        options:
          - full_regression
          - start_page
          - register_page
          - recovery_page

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Chrome
        run: sudo apt-get update -y && sudo apt-get install google-chrome-stable -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get install openjdk-11-jre-headless curl tar -y
          mkdir -p $HOME/bin
          curl -o allure-2.13.8.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz && \
          tar -zxvf allure-2.13.8.tgz -C $HOME/bin/
          echo "export PATH=\$HOME/bin/allure-2.13.8/bin:\$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Run Automated tests
        run: |
          # Depending on the deployment_target, run the appropriate set of tests
          if [ "${{ github.event.inputs.deployment_target }}" == "full_regression" ]; then
            pytest -sv TESTS/ --alluredir=allure-results || true
          elif [ "${{ github.event.inputs.deployment_target }}" == "start_page" ]; then
            pytest -sv TESTS/test_start_page.py --alluredir=allure-results || true
          elif [ "${{ github.event.inputs.deployment_target }}" == "register_page" ]; then
            pytest -sv TESTS/test_register_page.py --alluredir=allure-results || true
          elif [ "${{ github.event.inputs.deployment_target }}" == "recovery_page" ]; then
            pytest -sv TESTS/test_recovery_page.py --alluredir=allure-results || true
          else
            echo "Invalid deployment_target specified."
          fi

      - name: Generate Allure report
        run: |
          allure generate -c allure-results -o allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
