name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: full_regression
        type: choice
        options:
          - full_regression
          - start_page
          - register_page
          - recovery_page
#on:
#  push:
#    branches: [ "PagesMain" ]

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: full_regression
      if: "github.event.inputs.deployment_target == 'full_regression'"
      run: |
        pytest -sv TESTS/ --alluredir=allure-results || true

    - name: start_page
      if: "github.event.inputs.deployment_target == 'start_page'"
      run: |
        pytest -sv TESTS/test_start_page.py --alluredir=allure-results || true 

    - name: register_page
      if: "github.event.inputs.deployment_target == 'register_page'"
      run: |
        pytest -sv TESTS/test_register_page.py --alluredir=allure-results || true

    - name: recovery_page
      if: "github.event.inputs.deployment_target == 'recovery_page'"
      run: |
        pytest -sv TESTS/test_recovery_page.py --alluredir=allure-results || true

    - name: Store allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path:
          allure-results
        retention-days: 1


  Generate-report:
    runs-on: ubuntu-latest
    needs: Tests
    name: Generate report
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz && \
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/ && \
          sudo ln -s /opt/allure-2.24.1.tgz/bin/allure /usr/bin/allure && \
          sudo rm allure-2.24.1.tgz

      - name: Download artifacts
        uses: actions/download-artifact@v3
      - run: /bin/sh -c "allure generate allure-results --clean -o allure-report"
#      - run: allure generate -c allure-results -o _site

      - name: Store report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 1
