name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: second_test
        type: choice
        options:
          - first_test
          - second_test
          - all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clone the gh-pages branch
        run: git clone --branch gh-pages --single-branch https://github.com/eeefimov/FreenanceProject.git gh-pages

      - name: Download historical data
        run: cp -R gh-pages/history allure-results

      - name: first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest TESTS/test_api.py --alluredir=allure-results
        continue-on-error: true

      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_button.py::test_button_exist_2 --alluredir=allure-results
        continue-on-error: true

      - name: all
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Generate and Store Historical Report
        run: |
          allure generate -c allure-results -o _site
          cp -R allure-results/history allure-history
        continue-on-error: true

      - name: Store Historical Data as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-history
          path: allure-history
          retention-days: 1
